# ebatis config

datasource :
  _name : default
  _type : mysql
  _mode : pool                              # mode  connection | pool | cluster, default connection
  hostname : 127.0.0.1
  user : root
  password : **********
  database : test
  connectionLimit : 50

sql :
  mapper : ./sql/*.xml

sqlchain :
  transaction : true
  timeout : 3000
  printsql : false